######################################################################
#
# File name : tb_uart_loopback_compile.do
# Created on: Thu Jun 01 09:38:59 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/work
D:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim

D:\\modeltech64_2020.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_2020.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_2020.4\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../../rtl/uart_loopback.v" \
"../../../../../rtl/uart_rx.v" \
"../../../../../rtl/uart_tx.v" \
"../../../../../sim/tb/tb_uart_loopback.v" \


# compile glbl module
D:\\modeltech64_2020.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

