######################################################################
#
# File name : tb_uart_loopback.udo
# Created on: Wed May 31 15:59:44 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
