######################################################################
#
# File name : tb_uart_loopback_simulate.do
# Created on: Thu Jun 01 09:39:08 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_uart_loopback xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_uart_loopback_wave.do}

view wave
view structure
view signals

do {tb_uart_loopback.udo}

run 1000ns
